// Generated by CoffeeScript 1.6.3
(function() {
  var $, animate, chooser, left, load, moveTo, offset, right, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  offset = 300;

  $ = function(select) {
    return document.querySelector(select);
  };

  left = $('#left');

  right = $('#right');

  moveTo = function(pos) {
    var x, y, z;
    x = pos.x, y = pos.y, z = pos.z;
    if (x && y) {
      this.style.visibility = 'visible';
      this.cx.baseVal.value = x + offset;
      this.cy.baseVal.value = y;
      return this.r.baseVal.value = 25 + z / 10;
    } else {
      return this.style.visibility = 'hidden';
    }
  };

  left.moveTo = moveTo;

  right.moveTo = moveTo;

  animate = function(data) {
    var duration, last, run, step;
    last = data.length - 1;
    duration = (data[last].timestamp - data[0].timestamp) / 1000;
    step = duration / data.length;
    run = function() {
      var frame;
      window.requestAnimationFrame(run);
      if (data.length) {
        frame = data.shift();
        left.moveTo(frame.left.pos);
        return right.moveTo(frame.right.pos);
      }
    };
    return run();
  };

  load = function() {
    var File, reader;
    File = this.files[0];
    if (!File.type.match('\.json$')) {
      return;
    }
    file.textContent = File.name;
    reader = new FileReader();
    reader.onload = function(file) {
      var data;
      data = JSON.parse(this.result);
      return animate(data);
    };
    return reader.readAsText(File);
  };

  chooser = $('#chooser');

  chooser.addEventListener('change', load);

  $('#file').addEventListener('click', function() {
    return chooser.click();
  });

}).call(this);
