// Generated by CoffeeScript 1.6.3
(function() {
  var $, animate, left, load, moveTo, offset, right, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  offset = 300;

  $ = function(select) {
    return document.querySelector(select);
  };

  left = $('#left');

  right = $('#right');

  moveTo = function(pos) {
    var x, y, z;
    x = pos.x, y = pos.y, z = pos.z;
    if (x && y) {
      this.style.visibility = 'visible';
      this.cx.baseVal.value = x + offset;
      this.cy.baseVal.value = y;
      return this.r.baseVal.value = 25 + z / 10;
    } else {
      return this.style.visibility = 'hidden';
    }
  };

  left.moveTo = moveTo;

  right.moveTo = moveTo;

  animate = function(data) {
    var duration, last, run, step;
    last = data.length - 1;
    duration = (data[last].timestamp - data[0].timestamp) / 1000;
    step = duration / data.length;
    run = function() {
      var frame;
      if (data.length) {
        frame = data.shift();
        left.moveTo(frame.left.pos);
        right.moveTo(frame.right.pos);
        return setTimeout((function() {
          return window.requestAnimationFrame(run);
        }), step);
      }
    };
    return run();
  };

  load = function(path, done) {
    var xhr;
    xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function() {
      if ((xhr.readyState === 4) && (xhr.status === 200)) {
        return done(JSON.parse(xhr.responseText));
      }
    };
    xhr.open("GET", path, true);
    return xhr.send();
  };

  root.render = function(file) {
    return load(file, animate);
  };

}).call(this);
