// Generated by CoffeeScript 1.6.3
(function() {
  var h, moveTo, root, w;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  w = 300;

  h = 300;

  moveTo = function(pos) {
    var cx, cy, dy, r, x, y, z;
    x = pos.x, y = pos.y, z = pos.z;
    dy = y - 240;
    cy = (h / 2) - ((dy / 260) * (h / 2));
    cx = ((x / 260) * (w / 2)) + (w / 2);
    r = 15 + (z / 10);
    if (x && y) {
      this.style.visibility = 'visible';
      this.cx.baseVal.value = cx;
      this.cy.baseVal.value = cy;
      return this.r.baseVal.value = r;
    } else {
      return this.style.visibility = 'hidden';
    }
  };

  left.moveTo = moveTo;

  right.moveTo = moveTo;

  root.animate = function(data, width, height) {
    var i, run;
    if (width != null) {
      w = width;
    }
    if (height != null) {
      h = height;
    }
    hands.style.visibility = 'visible';
    i = 0;
    run = function() {
      var d;
      window.requestAnimationFrame(run);
      if (i < data.length) {
        d = data[i];
        left.moveTo(d.data('left'));
        right.moveTo(d.data('right'));
        return i += 1;
      }
    };
    return run();
  };

}).call(this);
