// Generated by CoffeeScript 1.6.3
(function() {
  var moveTo, offset, paused, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  paused = false;

  offset = 300;

  moveTo = function(pos) {
    var x, y, z;
    x = pos.x, y = pos.y, z = pos.z;
    if (x && y) {
      this.style.visibility = 'visible';
      this.cx.baseVal.value = x + offset;
      this.cy.baseVal.value = y;
      return this.r.baseVal.value = 25 + z / 10;
    } else {
      return this.style.visibility = 'hidden';
    }
  };

  left.moveTo = moveTo;

  right.moveTo = moveTo;

  root.animate = function(data) {
    var run;
    hands.style.visibility = 'visible';
    run = function() {
      var d;
      if (data.length && !paused) {
        window.requestAnimationFrame(run);
        d = data.shift();
        left.moveTo(d.data('left'));
        return right.moveTo(d.data('right'));
      }
    };
    return run();
  };

}).call(this);
